export const TOGGLE_MOBILE = "TOGGLE_MOBILE";
export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN";
export const PRODUCT_ARIA_EXPANDED = "PRODUCT_ARIA_EXPANDED";
export const RESOURCE_ARIA_EXPANDED = "RESOURCE_ARIA_EXPANDED";
export const ARIA_UNEXPANDED = "ARIA_UNEXPANDED";
